// lib/services/tsumugi_quote_service.dart

import 'dart:math';
import 'package:shared_preferences/shared_preferences.dart';

class TsumugiQuoteService {
  TsumugiQuoteService._();

  static final TsumugiQuoteService instance = TsumugiQuoteService._();

  static const int _historySize = 5;
  static final Random _rand = Random();

  static const Map<String, List<String>> _quotesByLocale = {
    'ja': [
      "おかえり ☕ ほっとしたら、ひとこと話そ？",
      "今日は短くていいよ。1分だけね。",
      "いい感じだよ。気楽にいこ？",
      "ゆっくりで大丈夫。少しだけ話そ。",
      "今日も来てくれてうれしいな。ひとことどう？",
      "ちょっとだけ、声かけてみる？",
      "小さな一言で十分だよ。今はそれでいこ？",
      "気分転換に、ひとことどう？",
      "焦らなくていいよ。今のままで話そ。",
      "自分のペースでいいよ。今日は一言だけね。",
      "ほっとしたら、軽くあいさつしてみよ？",
      "今日は短いフレーズからでOK。やってみる？",
      "ひとくちコーヒー気分で、ひとことどう？",
      "やさしく話してみよ。短くていいよ？",
      "いまの気分で、ひとことだけ言ってみる？",
      "まだ眠い？ それでも一言いけそう？",
      "軽く声を出すだけでも十分だよ。やってみる？",
      "気楽に、短い一言だけで進めよ？",
      "今日はここから。小さく始めよ？",
      "ひとこと練習、つきあってくれる？",
      "いいペースだよ。もう一言いけそう？",
      "今のまま、ちょっとだけ話そ？",
      "ひとことだけ、口をならそ？",
      "今日の気分で、短く返してみる？",
      "うんうん、その感じ。軽くひとことどう？",
      "ここで一息。短く話してみよ？",
      "ほんの少しだけ。声かけてみる？",
      "短い言葉でOK。今の気分でどう？",
      "やさしい一文で十分だよ。やってみる？",
      "今日はゆるめに。ひとことだけね？",
      "ひとこと言えたら、それでOK。試してみる？",
      "そっと始めよ。短い一言どう？",
      "ほっとする一言、言ってみる？",
      "まだ緊張してる？ 短くで大丈夫だよ。やってみる？",
      "今日は軽めで。ひとことだけでいい？",
      "少しだけ口を動かそう。ひとことどう？",
      "ふんわり返してみよ。短い一言でOK？",
      "ひとこと言ってみたら、きっと楽だよ。やってみる？",
      "ここはカフェ。気楽に一言だけね？",
      "いまの気持ちで、短く話してみる？",
      "ちょっとだけ声を出してみよ？すぐ終わるよ。",
      "今日は一言だけの練習にしよ？",
      "短い返事で十分。ひとことどう？",
      "優しい言い方でOK。軽くいこ？",
      "今日は一分メニュー。ひとこといける？",
      "ここから小さく。ひとこと言ってみる？",
      "ほっとしたら、ひとことから始めよ？",
      "いまのままで大丈夫。短く話そ？",
      "気が向いたら、ひとことだけどう？",
      "ねぇ、軽く話してみない？",
      "今日の一言、いっしょに言ってみる？",
      "ひとことだけでも、ちゃんと進んでるよ。もう一言どう？",
      "いまの声でいいよ。軽く言ってみる？",
      "今日は短い問いかけでOK。返してみる？",
      "小さな一言、ここで言ってみない？",
      "ふわっと話してみよ。短くていいよ？",
      "少しだけ会話の入口、作ってみる？",
      "ひとこと返してくれたらうれしいな。どう？",
      "今の気分で、軽くひとことどう？",
      "よかったら、短く答えてみる？",
    ],
    'en': [
      "Welcome back ☕ When you’re settled, want to say a quick line?",
      "Short is fine today. Just one minute, okay?",
      "You’re doing great. Want to keep it easy and try a line?",
      "No rush. Want to say just a little?",
      "I’m happy you’re here again. One quick line?",
      "Just a little—want to say something?",
      "One small line is enough. Shall we try?",
      "For a quick refresh, how about a short line?",
      "No need to hurry. Want to speak just as you are?",
      "Your pace is perfect. Just one line today?",
      "When you feel ready, want to try a quick greeting?",
      "We can start with a short phrase. Want to try?",
      "Like a sip of coffee, how about one line?",
      "A gentle line is plenty. Want to say it?",
      "With today’s mood, want to say just one line?",
      "Still sleepy? One tiny line anyway?",
      "Just warming up your voice is enough. Want to try?",
      "Keep it light—just a short line?",
      "Let’s start small. Ready for one line?",
      "Want to do a one‑line practice together?",
      "Nice pace. One more short line?",
      "Just as you are, want to say a little?",
      "A quick warm‑up line?",
      "With today’s mood, want to answer briefly?",
      "Yep, that’s the feeling. One quick line?",
      "Take a breath—want to say something short?",
      "Just a little. Want to speak a bit?",
      "A short word is enough. Want to try?",
      "A gentle sentence is plenty. Shall we?",
      "Let’s go easy today. Just one line?",
      "If you can say one line, that’s enough. Want to try?",
      "Let’s start softly—one short line?",
      "A calming line—want to say it?",
      "Feeling tense? Short is totally fine—want to try?",
      "Light mode today. One line okay?",
      "Move your mouth just a bit—one line?",
      "A soft reply is fine. One short line?",
      "Try a quick line—you might feel lighter. Want to?",
      "Café vibe here. One easy line?",
      "With your current feeling, want a short line?",
      "Just a tiny voice—one line? It’ll be quick.",
      "Let’s do a one‑line practice today?",
      "A short reply is enough. Want to try?",
      "A gentle wording is fine. Want to go lightly?",
      "One‑minute menu today—one line?",
      "Start small from here—one line?",
      "When you’re settled, start with one line?",
      "You’re good as you are. Want a short line?",
      "If you feel like it, just one line?",
      "Hey, want to say a quick line?",
      "Today’s line—want to say it together?",
      "Even one line is real progress. One more?",
      "Your voice is perfect. Want to say it lightly?",
      "A short prompt is fine today—want to answer?",
      "A small line here—want to say it?",
      "A soft line is fine—want to try?",
      "How about a tiny doorway to talk—one line?",
      "I’d be happy with a short reply—want to?",
      "With today’s mood, how about a quick line?",
      "If you feel like it, want to answer briefly?",
    ],
    'zh': [
      "回来啦 ☕ 休一会儿后，说一句好吗？",
      "今天短一点就好。1分钟可以吗？",
      "很不错哦。要不要轻松说一句？",
      "不着急。要不要说一点点？",
      "今天也来啦真开心。说一句好吗？",
      "只要一点点，想说一句吗？",
      "一小句就够了。试试看吗？",
      "换个心情，来一句怎么样？",
      "不用赶。就按现在这样说一句？",
      "按你的节奏来。今天一句就好？",
      "放松后，打个招呼试试？",
      "从短语开始就行。要不要试试？",
      "像喝一口咖啡那样，说一句？",
      "温柔地说就好。来一句吗？",
      "以现在的心情，先说一句？",
      "还困吗？一句小小的也可以？",
      "轻轻出声就够了。要不要试？",
      "轻松点，一小句就好？",
      "从这里小小开始，好吗？",
      "一句小练习，陪我来吗？",
      "节奏很好哦。再一句可以吗？",
      "就按现在这样，说一点点？",
      "先热个口，一句就好？",
      "按今天的心情，简短回一句？",
      "嗯嗯，就这个感觉。来一句好吗？",
      "先歇一下，短短说一句？",
      "就一点点，想说一句吗？",
      "短短的词就行。要不要来？",
      "温柔的一句就够。试试看？",
      "今天慢一点。一句就好？",
      "能说一句就很棒。要不要试？",
      "轻轻开始，一小句好吗？",
      "说一句让人放松的话，试试？",
      "还紧张吗？短一点也可以，来一句？",
      "今天轻量模式。一句可以吗？",
      "动动嘴就好。来一句？",
      "轻轻回答就行。一小句好吗？",
      "说一句就会轻松些。要不要试？",
      "这里像咖啡店。轻松一句好吗？",
      "以现在的感觉，短短说一句？",
      "轻轻出声，一句就好？很快的。",
      "今天练一句就好，好吗？",
      "简短的回应就够。来一句？",
      "温柔的说法就行。轻松来？",
      "今天是一分钟菜单。一句可以吗？",
      "从这里小小开始，说一句？",
      "放松后，从一句开始好吗？",
      "就按现在这样，短短说一句？",
      "想说的时候，一句就好？",
      "嘿，轻轻说一句好吗？",
      "今天的一句，一起说好吗？",
      "只说一句也很棒。再一句吗？",
      "现在的声音就很好。轻轻说一句？",
      "今天用短问题就好。回答一句？",
      "小小一句，在这里说说？",
      "软软地说一句，试试？",
      "先开个小口子，说一句好吗？",
      "你回一句我会很开心。可以吗？",
      "按现在的心情，轻轻一句？",
      "如果愿意，简短回一句？",
    ],
    'zh_TW': [
      "回來啦 ☕ 休一會兒後，說一句好嗎？",
      "今天短一點就好。1分鐘可以嗎？",
      "很不錯喔。要不要輕鬆說一句？",
      "不著急。要不要說一點點？",
      "今天也來啦真開心。說一句好嗎？",
      "只要一點點，想說一句嗎？",
      "一小句就夠了。試看看嗎？",
      "換個心情，來一句怎麼樣？",
      "不用趕。就按現在這樣說一句？",
      "按你的節奏來。今天一句就好？",
      "放鬆後，打個招呼試試？",
      "從短語開始就行。要不要試試？",
      "像喝一口咖啡那樣，說一句？",
      "溫柔地說就好。來一句嗎？",
      "以現在的心情，先說一句？",
      "還困嗎？一句小小的也可以？",
      "輕輕出聲就夠了。要不要試？",
      "輕鬆點，一小句就好？",
      "從這裡小小開始，好嗎？",
      "一句小練習，陪我來嗎？",
      "節奏很好喔。再一句可以嗎？",
      "就按現在這樣，說一點點？",
      "先熱個口，一句就好？",
      "按今天的心情，簡短回一句？",
      "嗯嗯，就這個感覺。來一句好嗎？",
      "先歇一下，短短說一句？",
      "就一點點，想說一句嗎？",
      "短短的詞就行。要不要來？",
      "溫柔的一句就夠。試看看？",
      "今天慢一點。一句就好？",
      "能說一句就很棒。要不要試？",
      "輕輕開始，一小句好嗎？",
      "說一句讓人放鬆的話，試試？",
      "還緊張嗎？短一點也可以，來一句？",
      "今天輕量模式。一句可以嗎？",
      "動動嘴就好。來一句？",
      "輕輕回答就行。一小句好嗎？",
      "說一句就會輕鬆些。要不要試？",
      "這裡像咖啡店。輕鬆一句好嗎？",
      "以現在的感覺，短短說一句？",
      "輕輕出聲，一句就好？很快的。",
      "今天練一句就好，好嗎？",
      "簡短的回應就夠。來一句？",
      "溫柔的說法就行。輕鬆來？",
      "今天是一分鐘菜單。一句可以嗎？",
      "從這裡小小開始，說一句？",
      "放鬆後，從一句開始好嗎？",
      "就按現在這樣，短短說一句？",
      "想說的時候，一句就好？",
      "嘿，輕輕說一句好嗎？",
      "今天的一句，一起說好嗎？",
      "只說一句也很棒。再一句嗎？",
      "現在的聲音就很好。輕輕說一句？",
      "今天用短問題就好。回答一句？",
      "小小一句，在這裡說說？",
      "軟軟地說一句，試試？",
      "先開個小口子，說一句好嗎？",
      "你回一句我會很開心。可以嗎？",
      "按現在的心情，輕輕一句？",
      "如果願意，簡短回一句？",
    ],
    'ko': [
      "다녀왔어 ☕ 쉬었다가 한마디 할래?",
      "오늘은 짧게만 해도 돼. 1분만 할까?",
      "좋아, 느낌 좋아. 편하게 한마디 해볼래?",
      "서두르지 않아도 돼. 조금만 말해볼까?",
      "오늘도 와줘서 기뻐. 한마디 해줄래?",
      "조금만, 살짝 말해볼래?",
      "짧은 한마디면 충분해. 해볼까?",
      "기분 전환으로 한마디 어때?",
      "급하지 않아도 돼. 지금 그대로 한마디 해볼까?",
      "네 페이스면 충분해. 오늘 한마디만?",
      "편해지면 가벼운 인사 한번 해볼래?",
      "짧은 문장부터 시작해도 돼. 해볼까?",
      "커피 한 모금처럼, 한마디 어때?",
      "부드럽게 말하면 돼. 짧게 해볼래?",
      "지금 기분으로 한마디만 해볼래?",
      "아직 졸려? 그래도 한마디 가능할까?",
      "가볍게 소리 내는 것만으로도 충분해. 해볼래?",
      "편하게, 짧은 한마디만 해볼까?",
      "여기서 작게 시작하자. 한마디 해볼래?",
      "한마디 연습, 같이 해줄래?",
      "페이스 좋아. 한마디 더 해볼래?",
      "지금 그대로, 조금만 말해볼까?",
      "입 풀기용으로 한마디만 해볼래?",
      "오늘 기분대로 짧게 답해볼래?",
      "응응, 그 느낌. 가볍게 한마디 어때?",
      "잠깐 쉬고 짧게 말해볼까?",
      "아주 조금만. 한마디 해볼래?",
      "짧은 말이면 돼. 지금 기분 어때?",
      "부드러운 한 문장이면 충분해. 해볼래?",
      "오늘은 느슨하게. 한마디만 할까?",
      "한마디만 해도 충분해. 해볼래?",
      "살짝 시작해보자. 짧게 한마디 어때?",
      "마음 풀리는 한마디, 말해볼래?",
      "아직 긴장돼? 짧게 해도 괜찮아. 해볼까?",
      "오늘은 라이트 모드. 한마디만 할래?",
      "입만 살짝 움직여도 돼. 한마디 어때?",
      "부드럽게 답해도 돼. 짧은 한마디 어때?",
      "한마디 해보면 마음이 가벼워질 거야. 해볼래?",
      "여긴 카페야. 편하게 한마디만 할래?",
      "지금 기분으로 짧게 말해볼래?",
      "조금만 목소리 내볼래? 금방 끝나.",
      "오늘은 한마디 연습만 해볼까?",
      "짧은 대답이면 충분해. 한마디 해볼래?",
      "부드러운 말투면 돼. 가볍게 갈까?",
      "오늘은 1분 메뉴야. 한마디 가능해?",
      "여기서 작게 시작해볼래? 한마디만.",
      "편해지면 한마디부터 시작해볼까?",
      "지금 그대로면 돼. 짧게 말해볼래?",
      "마음 내키면 한마디만 해볼래?",
      "저기, 가볍게 한마디 해볼래?",
      "오늘의 한마디, 같이 말해볼래?",
      "한마디만 해도 충분히 진행 중이야. 한마디 더?",
      "지금 목소리로 충분해. 가볍게 말해볼래?",
      "오늘은 짧은 질문이면 돼. 답해볼래?",
      "작은 한마디, 여기서 말해볼래?",
      "살짝 말해보자. 짧게 해도 돼?",
      "대화의 입구를 조금만 열어볼래?",
      "한마디 답해주면 기쁠 것 같아. 해줄래?",
      "지금 기분으로 가볍게 한마디 어때?",
      "괜찮으면 짧게 답해볼래?",
    ],
    'es': [
      "Bienvenida ☕ Cuando estés lista, ¿dices una frase?",
      "Hoy puede ser corto. ¿Un minuto nada más?",
      "Vas muy bien. ¿Lo hacemos suave con una frase?",
      "Sin prisa. ¿Dices solo un poquito?",
      "Me alegra que estés aquí. ¿Una frase rápida?",
      "Solo un poquito, ¿quieres decir algo?",
      "Con una frase pequeña basta. ¿Probamos?",
      "Para cambiar de aire, ¿una frase?",
      "No hay que correr. ¿Hablamos tal como estás?",
      "Tu ritmo está perfecto. ¿Solo una frase hoy?",
      "Cuando te apetezca, ¿saludamos con una frase?",
      "Podemos empezar con una frase corta. ¿Te parece?",
      "Como un sorbito de café, ¿una frase?",
      "Con suavidad está bien. ¿La dices corta?",
      "Con el ánimo de hoy, ¿dices una frase?",
      "¿Aún con sueño? ¿Una mini frase igual?",
      "Solo calentar la voz ya basta. ¿Lo intentas?",
      "Ligero y corto, ¿una frase?",
      "Empecemos pequeño. ¿Una frase?",
      "¿Hacemos una práctica de una frase juntas?",
      "Buen ritmo. ¿Una frase más?",
      "Tal como estás, ¿dices un poquito?",
      "¿Una frase para calentar?",
      "Con tu ánimo de hoy, ¿respondes breve?",
      "Sí, ese es el tono. ¿Una frase rápida?",
      "Respira un poquito, ¿dices algo corto?",
      "Solo un poquito. ¿Hablamos un poco?",
      "Una palabra corta basta. ¿Te animas?",
      "Una frase suave es suficiente. ¿Vamos?",
      "Hoy en modo ligero. ¿Solo una frase?",
      "Si dices una frase, ya está. ¿Probamos?",
      "Empecemos suave. ¿Una frase corta?",
      "Una frase que relaje, ¿la dices?",
      "¿Estás nerviosa? Cortito está bien. ¿Probamos?",
      "Hoy suavecito. ¿Una frase?",
      "Solo mover la boca un poco. ¿Una frase?",
      "Una respuesta suave está bien. ¿Una frase corta?",
      "Si dices una frase, te sentirás más ligera. ¿Te animas?",
      "Esto es un café. ¿Una frase sin presión?",
      "Con tu ánimo de ahora, ¿una frase corta?",
      "Solo una pequeña voz, ¿una frase? Es rápido.",
      "¿Hoy practicamos solo una frase?",
      "Con una respuesta corta basta. ¿Una frase?",
      "Con palabras suaves está bien. ¿Vamos ligero?",
      "Menú de un minuto hoy. ¿Una frase?",
      "Desde aquí, empezamos pequeño. ¿Una frase?",
      "Cuando estés tranquila, empezamos con una frase?",
      "Tal como estás, ¿hablamos corto?",
      "Si te apetece, ¿una frase nada más?",
      "Oye, ¿te animas a decir una frase?",
      "La frase de hoy, ¿la decimos juntas?",
      "Una frase ya es progreso. ¿Otra más?",
      "Tu voz ahora es perfecta. ¿La dices suave?",
      "Hoy vale una pregunta corta. ¿Respondes?",
      "Una frase pequeñita aquí, ¿la dices?",
      "Con suavidad, ¿una frase corta?",
      "¿Abrimos un poquito la conversación con una frase?",
      "Me haría feliz una respuesta breve, ¿quieres?",
      "Con tu ánimo de hoy, ¿una frase ligera?",
      "Si te parece, ¿respondes cortito?",
    ],
    'fr': [
      "Te revoilà ☕ Quand tu es prête, tu dis une petite phrase ?",
      "Aujourd’hui, court c’est bien. Une minute seulement ?",
      "Tu vas super bien. On y va tout doux avec une phrase ?",
      "Pas de stress. Tu dis juste un petit peu ?",
      "Contente de te voir. Une petite phrase ?",
      "Juste un tout petit peu, tu veux dire quelque chose ?",
      "Une petite phrase suffit. On essaie ?",
      "Pour changer d’air, une phrase ?",
      "Pas besoin de se presser. On parle comme tu es ?",
      "Ton rythme est parfait. Une seule phrase aujourd’hui ?",
      "Quand tu te sens prête, on tente un petit salut ?",
      "On peut commencer par une phrase courte. Ça te va ?",
      "Comme une gorgée de café, une phrase ?",
      "Doucement, c’est très bien. Tu la dis courte ?",
      "Avec l’humeur du jour, tu dis une phrase ?",
      "Encore un peu endormie ? Une mini phrase quand même ?",
      "Juste échauffer la voix suffit. Tu veux essayer ?",
      "Léger et court, une phrase ?",
      "On commence petit. Une phrase ?",
      "On fait un exercice d’une phrase ensemble ?",
      "Beau rythme. Une phrase de plus ?",
      "Comme tu es là, tu dis juste un petit peu ?",
      "Une phrase pour se mettre en route ?",
      "Avec ton humeur d’aujourd’hui, tu réponds brièvement ?",
      "Oui, ce ton-là. Une phrase rapide ?",
      "On respire, puis une phrase courte ?",
      "Tout petit peu. Tu veux parler un peu ?",
      "Un mot court suffit. Tu veux essayer ?",
      "Une phrase douce, c’est suffisant. On y va ?",
      "Aujourd’hui en mode léger. Une phrase seulement ?",
      "Si tu dis une phrase, c’est déjà bien. On tente ?",
      "On commence doucement. Une courte phrase ?",
      "Une phrase qui apaise, tu la dis ?",
      "Un peu stressée ? Court c’est OK. On essaye ?",
      "Aujourd’hui, tout doux. Une phrase ?",
      "Juste bouger la bouche un peu. Une phrase ?",
      "Une réponse douce, c’est parfait. Une courte phrase ?",
      "Dis une phrase, ça allège. Tu veux essayer ?",
      "Ici, c’est un café. Une phrase tranquille ?",
      "Avec ton ressenti, une phrase courte ?",
      "Juste un petit souffle, une phrase ? C’est rapide.",
      "Aujourd’hui, on s’entraîne avec une seule phrase ?",
      "Une réponse courte suffit. Une phrase ?",
      "Des mots doux, c’est très bien. On y va léger ?",
      "Menu d’une minute aujourd’hui. Une phrase ?",
      "On commence petit ici. Une phrase ?",
      "Quand tu es posée, on commence par une phrase ?",
      "Comme tu es, une phrase courte ?",
      "Si tu as envie, une petite phrase ?",
      "Hé, tu veux dire une phrase ?",
      "La phrase du jour, on la dit ensemble ?",
      "Une phrase, c’est déjà un progrès. Une autre ?",
      "Ta voix est parfaite. Tu la dis tout doux ?",
      "Aujourd’hui, une question courte suffit. Tu réponds ?",
      "Une petite phrase ici, tu la dis ?",
      "Tout doux, une phrase courte ?",
      "On ouvre la conversation avec une phrase ?",
      "Une réponse brève me ferait plaisir. Tu veux ?",
      "Avec ton humeur, une phrase légère ?",
      "Si tu veux, tu réponds tout court ?",
    ],
    'de': [
      "Willkommen zurück ☕ Wenn du bereit bist, magst du eine kurze Zeile sagen?",
      "Heute darf es kurz sein. Nur eine Minute, okay?",
      "Du machst das gut. Wollen wir es locker mit einer Zeile probieren?",
      "Kein Stress. Magst du nur ein bisschen sagen?",
      "Schön, dass du da bist. Eine kurze Zeile?",
      "Nur ein kleines bisschen – willst du etwas sagen?",
      "Eine kleine Zeile reicht. Wollen wir?",
      "Für einen kleinen Wechsel – eine kurze Zeile?",
      "Kein Eilen. Wollen wir so sprechen, wie du gerade bist?",
      "Dein Tempo ist perfekt. Heute nur eine Zeile?",
      "Wenn du soweit bist, magst du kurz grüßen?",
      "Wir können mit einem kurzen Satz starten. Lust?",
      "Wie ein Schluck Kaffee – eine Zeile?",
      "Ganz sanft reicht. Magst du sie kurz sagen?",
      "Mit der Stimmung von heute – eine Zeile?",
      "Noch müde? Trotzdem eine Mini‑Zeile?",
      "Die Stimme nur kurz anwärmen reicht. Magst du?",
      "Ganz locker – nur eine kurze Zeile?",
      "Wir starten klein. Eine Zeile?",
      "Eine Ein‑Zeilen‑Übung zusammen?",
      "Gutes Tempo. Noch eine kleine Zeile?",
      "So wie du bist – magst du ein wenig sagen?",
      "Eine kurze Aufwärm‑Zeile?",
      "Mit der Stimmung von heute, magst du kurz antworten?",
      "Ja, genau so. Eine schnelle Zeile?",
      "Einmal durchatmen – dann eine kurze Zeile?",
      "Nur ein bisschen. Magst du etwas sagen?",
      "Ein kurzes Wort reicht. Willst du’s probieren?",
      "Ein sanfter Satz genügt. Wollen wir?",
      "Heute im leichten Modus. Nur eine Zeile?",
      "Eine Zeile genügt schon. Wollen wir’s versuchen?",
      "Sanft starten. Eine kurze Zeile?",
      "Eine beruhigende Zeile – magst du sie sagen?",
      "Noch nervös? Kurz ist völlig okay. Versuchst du’s?",
      "Heute ganz leicht. Eine Zeile?",
      "Nur den Mund kurz bewegen – eine Zeile?",
      "Eine sanfte Antwort reicht. Eine kurze Zeile?",
      "Eine Zeile sagen macht’s leichter. Magst du?",
      "Hier ist Café‑Stimmung. Eine lockere Zeile?",
      "Mit deinem jetzigen Gefühl – eine kurze Zeile?",
      "Nur eine kleine Stimme – eine Zeile? Geht ganz schnell.",
      "Heute nur eine Zeile üben?",
      "Eine kurze Antwort reicht. Eine Zeile?",
      "Sanfte Worte sind gut. Wollen wir locker bleiben?",
      "Heute ein Ein‑Minuten‑Menü. Eine Zeile?",
      "Hier klein anfangen. Eine Zeile?",
      "Wenn du bereit bist, starten wir mit einer Zeile?",
      "So wie du bist – eine kurze Zeile?",
      "Wenn du magst, nur eine Zeile?",
      "Hey, magst du eine kurze Zeile sagen?",
      "Die Zeile des Tages – sagen wir sie zusammen?",
      "Eine Zeile ist schon Fortschritt. Noch eine?",
      "Deine Stimme ist genau richtig. Magst du sie sanft sagen?",
      "Heute reicht eine kurze Frage. Antwortest du?",
      "Eine kleine Zeile hier – magst du sie sagen?",
      "Ganz sanft – eine kurze Zeile?",
      "Öffnen wir den Gesprächseinstieg mit einer Zeile?",
      "Über eine kurze Antwort würde ich mich freuen. Magst du?",
      "Mit deiner Stimmung heute – eine leichte Zeile?",
      "Wenn du möchtest, antworte kurz?",
    ],
    'vi': [
      "Chào mừng quay lại ☕ Nghỉ một chút rồi nói một câu nhé?",
      "Hôm nay ngắn thôi cũng được. Chỉ 1 phút nhé?",
      "Bạn làm tốt lắm. Mình nói nhẹ nhàng một câu nhé?",
      "Không vội đâu. Nói một chút thôi nhé?",
      "Vui vì bạn ghé lại. Nói một câu nhỏ nhé?",
      "Chỉ một chút thôi, bạn nói thử được không?",
      "Một câu ngắn là đủ. Thử nhé?",
      "Đổi chút không khí, nói một câu nhé?",
      "Không cần gấp. Nói theo đúng cảm giác bây giờ nhé?",
      "Nhịp của bạn rất ổn. Hôm nay một câu thôi nhé?",
      "Khi thấy thoải mái, mình chào nhẹ một câu nhé?",
      "Bắt đầu bằng câu ngắn được rồi. Thử nhé?",
      "Như nhấp một ngụm cà phê, nói một câu nhé?",
      "Nói nhẹ nhàng là được. Câu ngắn thôi nhé?",
      "Với tâm trạng hôm nay, nói một câu nhé?",
      "Còn buồn ngủ à? Một câu nhỏ cũng được nhé?",
      "Chỉ cần làm ấm giọng thôi. Thử một câu nhé?",
      "Nhẹ nhàng thôi, một câu ngắn nhé?",
      "Bắt đầu nhỏ từ đây nhé? Một câu thôi?",
      "Luyện một câu cùng mình nhé?",
      "Nhịp tốt đó. Thêm một câu nữa nhé?",
      "Cứ như hiện tại, nói một chút nhé?",
      "Khởi động miệng bằng một câu nhé?",
      "Theo tâm trạng hôm nay, trả lời ngắn nhé?",
      "Ừ, đúng cảm giác đó. Một câu nhanh nhé?",
      "Hít thở chút rồi nói câu ngắn nhé?",
      "Chỉ một chút thôi. Nói một câu nhé?",
      "Một từ ngắn cũng đủ. Thử nhé?",
      "Một câu dịu nhẹ là đủ. Thử nhé?",
      "Hôm nay nhẹ thôi. Một câu nhé?",
      "Nói được một câu là đủ rồi. Thử nhé?",
      "Bắt đầu thật nhẹ. Một câu ngắn nhé?",
      "Một câu làm dịu lòng, nói thử nhé?",
      "Còn hồi hộp à? Ngắn thôi cũng được. Thử nhé?",
      "Hôm nay chế độ nhẹ. Một câu nhé?",
      "Chỉ cần cử động miệng chút. Một câu nhé?",
      "Trả lời nhẹ thôi cũng được. Một câu ngắn nhé?",
      "Nói một câu là nhẹ người hơn đó. Thử nhé?",
      "Ở đây như quán cà phê. Một câu nhẹ nhàng nhé?",
      "Theo cảm giác hiện tại, nói ngắn nhé?",
      "Chỉ một chút giọng thôi. Một câu nhé? Nhanh thôi.",
      "Hôm nay luyện đúng một câu nhé?",
      "Trả lời ngắn là đủ. Một câu nhé?",
      "Cách nói dịu là được. Mình nói nhẹ nhé?",
      "Hôm nay menu 1 phút. Một câu nhé?",
      "Bắt đầu nhỏ từ đây. Một câu nhé?",
      "Khi thấy thoải mái, bắt đầu bằng một câu nhé?",
      "Cứ như hiện tại là được. Nói ngắn nhé?",
      "Nếu muốn, một câu thôi nhé?",
      "Này, nói nhẹ một câu nhé?",
      "Câu hôm nay, mình nói cùng nhé?",
      "Một câu thôi cũng là tiến bộ. Thêm một câu nhé?",
      "Giọng của bạn rất ổn. Nói nhẹ một câu nhé?",
      "Hôm nay chỉ cần câu hỏi ngắn. Trả lời nhé?",
      "Một câu nhỏ ở đây, nói thử nhé?",
      "Nói khẽ thôi, câu ngắn nhé?",
      "Mở nhẹ cánh cửa trò chuyện bằng một câu nhé?",
      "Mình sẽ vui nếu bạn trả lời ngắn. Được không?",
      "Theo tâm trạng hôm nay, một câu nhẹ nhé?",
      "Nếu bạn muốn, trả lời ngắn nhé?",
    ],
    'id': [
      "Selamat datang kembali ☕ Setelah rileks, mau bilang satu kalimat?",
      "Hari ini singkat saja. Cuma 1 menit, ya?",
      "Bagus banget. Mau santai dengan satu kalimat?",
      "Tidak perlu buru‑buru. Mau bilang sedikit saja?",
      "Senang kamu datang lagi. Satu kalimat, mau?",
      "Cuma sedikit, mau bilang sesuatu?",
      "Satu kalimat kecil sudah cukup. Yuk coba?",
      "Biar segar, satu kalimat gimana?",
      "Tidak usah cepat‑cepat. Mau bicara apa adanya?",
      "Pace‑mu pas. Hari ini satu kalimat saja?",
      "Kalau sudah siap, mau salam singkat?",
      "Kita mulai dari frasa pendek. Mau coba?",
      "Seperti seteguk kopi, satu kalimat yuk?",
      "Lembut saja cukup. Mau bilang pendek?",
      "Dengan mood hari ini, mau bilang satu kalimat?",
      "Masih ngantuk? Satu kalimat kecil juga boleh?",
      "Cukup menghangatkan suara. Mau coba?",
      "Santai saja, satu kalimat pendek?",
      "Mulai kecil dari sini. Satu kalimat?",
      "Latihan satu kalimat bareng, mau?",
      "Ritmemu bagus. Satu kalimat lagi?",
      "Apa adanya saja, mau bilang sedikit?",
      "Pemanasan mulut dengan satu kalimat?",
      "Sesuai mood hari ini, jawab singkat?",
      "Iya, itu rasanya. Satu kalimat cepat?",
      "Tarik napas dulu, lalu satu kalimat pendek?",
      "Sedikit saja. Mau bicara sebentar?",
      "Kata pendek saja cukup. Mau coba?",
      "Satu kalimat lembut sudah cukup. Yuk?",
      "Hari ini santai dulu. Satu kalimat saja?",
      "Kalau bisa satu kalimat, sudah cukup. Mau coba?",
      "Mulai pelan. Satu kalimat pendek?",
      "Kalimat yang menenangkan, mau bilang?",
      "Masih tegang? Pendek saja tidak apa‑apa. Mau coba?",
      "Mode ringan hari ini. Satu kalimat?",
      "Gerakkan mulut sedikit saja. Satu kalimat?",
      "Jawab pelan juga boleh. Satu kalimat pendek?",
      "Coba satu kalimat, rasanya lebih ringan. Mau?",
      "Di sini vibe kafe. Satu kalimat santai?",
      "Dengan perasaan sekarang, satu kalimat pendek?",
      "Suara kecil saja. Satu kalimat? Cepat kok.",
      "Hari ini latihan satu kalimat saja?",
      "Jawaban singkat cukup. Satu kalimat?",
      "Kata‑kata lembut saja. Mau santai?",
      "Menu satu menit hari ini. Satu kalimat?",
      "Mulai kecil dari sini. Satu kalimat?",
      "Kalau sudah tenang, mulai dari satu kalimat?",
      "Apa adanya saja. Mau bicara singkat?",
      "Kalau mau, satu kalimat saja?",
      "Hei, mau bilang satu kalimat?",
      "Kalimat hari ini, mau bilang bareng?",
      "Satu kalimat saja sudah progres. Satu lagi?",
      "Suaramu sudah pas. Mau bilang pelan?",
      "Hari ini cukup pertanyaan singkat. Mau jawab?",
      "Satu kalimat kecil di sini, mau bilang?",
      "Pelan saja, kalimat pendek?",
      "Buka pintu ngobrol sedikit—satu kalimat?",
      "Aku senang kalau kamu jawab singkat. Mau?",
      "Dengan mood hari ini, satu kalimat ringan?",
      "Kalau berkenan, jawab singkat ya?",
    ],
  };

  String _resolveLocaleKey(String? raw) {
    if (raw == null || raw.trim().isEmpty) return 'ja';
    final normalized = raw.replaceAll('-', '_');
    if (_quotesByLocale.containsKey(normalized)) return normalized;
    final base = normalized.split('_').first;
    if (_quotesByLocale.containsKey(base)) return base;
    return 'ja';
  }

  Future<String> getNextQuote() async {
    final prefs = await SharedPreferences.getInstance();
    final localeKey = _resolveLocaleKey(prefs.getString('user_language'));
    final quotes = _quotesByLocale[localeKey] ?? _quotesByLocale['ja']!;
    final historyKey = 'tsumugi_quote_history_$localeKey';
    final history = prefs.getStringList(historyKey) ?? <String>[];

    final candidates = quotes.where((q) => !history.contains(q)).toList();
    final pool = candidates.isNotEmpty ? candidates : quotes;
    final quote = pool[_rand.nextInt(pool.length)];

    final updated = <String>[quote, ...history.where((q) => q != quote)];
    final trimmed = updated.length > _historySize
        ? updated.sublist(0, _historySize)
        : updated;
    await prefs.setStringList(historyKey, trimmed);
    return quote;
  }
}
