// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABJmKCyz7z8d0BPUWsYrLIrLhCCxrxHb8',
    appId: '1:112506097576:web:92f699b017e6908fe5d79d',
    messagingSenderId: '112506097576',
    projectId: 'kawaii-language-chat',
    authDomain: 'kawaii-language-chat.firebaseapp.com',
    storageBucket: 'kawaii-language-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABJmKCyz7z8d0BPUWsYrLIrLhCCxrxHb8',
    appId: '1:112506097576:android:f003faf5aead3f0ae5d79d',
    messagingSenderId: '112506097576',
    projectId: 'kawaii-language-chat',
    storageBucket: 'kawaii-language-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABJmKCyz7z8d0BPUWsYrLIrLhCCxrxHb8',
    appId: '1:112506097576:ios:8949d12cf1d7e6dae5d79d',
    messagingSenderId: '112506097576',
    projectId: 'kawaii-language-chat',
    storageBucket: 'kawaii-language-chat.firebasestorage.app',
    iosBundleId: 'com.kawaiilang.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABJmKCyz7z8d0BPUWsYrLIrLhCCxrxHb8',
    appId: '1:112506097576:ios:16b37a1be295d8dce5d79d',
    messagingSenderId: '112506097576',
    projectId: 'kawaii-language-chat',
    storageBucket: 'kawaii-language-chat.firebasestorage.app',
    iosBundleId: 'com.example.kawaiiLanguageChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABJmKCyz7z8d0BPUWsYrLIrLhCCxrxHb8',
    appId: '1:112506097576:web:1a58e9e619e6f922e5d79d',
    messagingSenderId: '112506097576',
    projectId: 'kawaii-language-chat',
    authDomain: 'kawaii-language-chat.firebaseapp.com',
    storageBucket: 'kawaii-language-chat.firebasestorage.app',
  );
}
